### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [lkcz04185/splurty_lk#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by lkcz04185** [comment]
Hi Billy,
thx for the good feedback. Did you have this tag on mind:
<meta name="viewport" content="width=device-width, initial-scale=1.0">.
The other thing I've noticed is that contributing a new quote from my android mobile device doesn't work.
The pop-up form stays after entering the quote and and pressing the Add Quote button. When I press Close button it disappears but the new quote doesn't get uploaded, whereas it works on the windows device. Any idea what might be wrong.

**Comment by BillyMassey** [comment]
Getting things perfect on all the different mobile manufacturers can be a little bit of a challenge.  Right now your app looks like it works well on most mobile devices, so I'd say keep it how it currently is and move on to building the next app, the nomster application.
